# Generated by Django 4.0.4 on 2022-05-03 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.IntegerField()),
                ('assigned_to_user_id', models.IntegerField()),
                ('created_by_user_id', models.IntegerField()),
                ('last_updated_by_user_id', models.IntegerField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 5, 3, 15, 40, 56, 2217, tzinfo=utc))),
                ('last_updated_date', models.DateTimeField(default='')),
            ],
        ),
    ]
