# Generated by Django 4.0.4 on 2022-05-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0002_alter_task_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_updated_date',
            field=models.DateTimeField(),
        ),
    ]
