# Generated by Django 4.0.4 on 2022-05-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0003_alter_task_date_created_alter_task_last_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_updated_by_user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_updated_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
